### ISSUE TITLE
Feature request: ability to lock app icons

### ISSUE THREAD

**Issue by yuliskov** [alescdb/LauncherTV#1]
Hi. Thanks for the great launcher. Sometimes there is useful to protect app icons from edition, deletion etc. For example, I could give tv box to my father. As he is not skilled enough, there may have place accident deletion of app icons or other stuff. Most of the launchers lack this feature but, I couldn't imagine good launcher without it. It would be implemented as settings check box. After checking, main icons can only be launched, but not changed, added, removed. What would say about this?

**Comment by alescdb** [comment]
Hi,
It seems pretty easy to implement, I'll give it a try !

**Comment by yuliskov** [comment]
Thanks

**Comment by goodplanet2012** [comment]
What is the status of the lock feature? I Second that! I made box for grandma and she always accidentally screw icons. I say check box is good idea! but at least there could be that you have to hold 5-10 seconds in order to change icons. Any idea is it possible to do? I could send small donation if you would do that!:)

**Comment by alescdb** [comment]
Done !
